#!/usr/bin/env python3
"""Write viewer/servers.js (committed: the public list of Doom servers and their input relays).

Usage: python3 tools/servers_config.py assets/servers.json
  servers.json: {"servers": [{"name": "...", "addr": "...", "relays": ["...", ...]}, ...], "demo": {"name": "...", "addr": "..."}}
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def main(argv=None):
    argv = argv or sys.argv[1:]
    src = argv[0] if argv else os.path.join(HERE, "..", "assets", "servers.json")
    with open(src) as f:
        cfg = json.load(f)
    out = os.path.join(HERE, "..", "viewer", "servers.js")
    with open(out, "w") as f:
        f.write("// generated by tools/servers_config.py from assets/servers.json: the public Doom servers (testnet)\n")
        f.write("window.DOOM_SERVERS = " + json.dumps(cfg, indent=1) + ";\n")
    print("wrote", os.path.normpath(out), "servers:", len(cfg["servers"]), "relays:", sum(len(s["relays"]) for s in cfg["servers"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
