#!/usr/bin/env python3
"""Write viewer/config.js from .env (DOOM_ADDRESS, TONCENTER_TESTNET_API_KEY, optional DOOM_RELAYS=a,b,c).
The file is git-ignored.

Usage: python3 tools/viewer_config.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from toncenter import _load_dotenv  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    env = dict(_load_dotenv())
    env.update({k: v for k, v in os.environ.items() if k in ("DOOM_ADDRESS", "DOOM_RELAYS", "TONCENTER_TESTNET_API_KEY", "TONCENTER_API_KEY")})
    relays = [a.strip() for a in env.get("DOOM_RELAYS", "").split(",") if a.strip()]
    cfg = {"addr": env.get("DOOM_ADDRESS", ""), "key": env.get("TONCENTER_TESTNET_API_KEY") or env.get("TONCENTER_API_KEY", ""), "relays": relays}
    out = os.path.join(HERE, "..", "viewer", "config.js")
    with open(out, "w") as f:
        f.write("// generated by tools/viewer_config.py from .env — do not commit\n")
        f.write("window.DOOM_CONFIG = " + json.dumps(cfg) + ";\n")
    print("wrote", os.path.normpath(out), "addr:", cfg["addr"] or "(none)", "key:", "set" if cfg["key"] else "(none)", "relays:", len(relays))
    return 0


if __name__ == "__main__":
    sys.exit(main())
